#!/usr/local/bin/node

var fs = require('fs');

var contents = "intro tty".split(' ');
var allMeta = {}; 

contents.forEach(function(name) {
    var path = '../content/' + name;
    var m = require(path);
    allMeta[name] = m.getMeta();
    var html = m.getHTML();
    fs.writeFileSync('./build/' + name + '.html', html, 'utf-8');
});


fs.writeFileSync('./build/meta.json', JSON.stringify(allMeta), 'utf-8');
